spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/identity_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # Atualiza o banco de dados conforme as mudanças nas entidades
    show-sql: true # Exibe as consultas SQL no log
