name: Auto Pull Request

on:
  workflow_run:
    workflows: ["Build and Test"]
    types:
      - completed
    branches:
      - 'feature/**'

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      pull-requests: write
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: develop
          title: 'Feature: ${{ github.event.workflow_run.head_branch }}'
          body: |
            Automatic pull request created from feature branch
            
            Changes made in this PR:
            - Build and tests passed successfully
          draft: false
          delete-branch: false 